import { linkEmailDestination, requestEmailCode, verifyEmailCode } from './member-email-auth.mjs';
import { storeMemberNotificationDestination } from './member-notification-delivery.mjs';
const encoder=new TextEncoder(),decoder=new TextDecoder();
const OAUTH_COOKIE='hoshilu_line_oauth',SESSION_COOKIE='hoshilu_member_session';
function b64(bytes){let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte);return btoa(binary).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'');}
function unb64(value){const normalized=value.replace(/-/g,'+').replace(/_/g,'/');const binary=atob(normalized+'='.repeat((4-normalized.length%4)%4));return Uint8Array.from(binary,char=>char.charCodeAt(0));}
async function sign(value,secret){const key=await crypto.subtle.importKey('raw',encoder.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64(new Uint8Array(await crypto.subtle.sign('HMAC',key,encoder.encode(value))));}
async function pack(payload,secret){const body=b64(encoder.encode(JSON.stringify(payload)));return`${body}.${await sign(body,secret)}`;}
async function unpack(value,secret){const[body,signature,extra]=String(value||'').split('.');if(!body||!signature||extra||await sign(body,secret)!==signature)throw new Error('MEMBER_COOKIE_INVALID');const payload=JSON.parse(decoder.decode(unb64(body)));if(!Number.isFinite(payload.exp)||payload.exp<Math.floor(Date.now()/1000))throw new Error('MEMBER_COOKIE_EXPIRED');return payload;}
function cookie(request,name){const row=String(request.headers.get('cookie')||'').split(';').map(item=>item.trim()).find(item=>item.startsWith(`${name}=`));return row?decodeURIComponent(row.slice(name.length+1)):'';}
function sessionSecret(env){const value=String(env.MEMBER_SESSION_SECRET||env.LINK_SIGNING_SECRET||'');if(value.length<32)throw new Error('MEMBER_SESSION_SECRET_REQUIRED');return value;}
function random(size=32){const bytes=new Uint8Array(size);crypto.getRandomValues(bytes);return b64(bytes);}
async function sha(value){return b64(new Uint8Array(await crypto.subtle.digest('SHA-256',encoder.encode(value))));}
function publicOrigin(env={}){const configured=String(env.MEMBER_PUBLIC_ORIGIN||'https://hoshilu.app').trim();try{const url=new URL(configured);return url.protocol==='https:'?url.origin:'https://hoshilu.app';}catch{return'https://hoshilu.app';}}
function callback(env){return`${publicOrigin(env)}/api/member/line/callback`;}
function safeReturnTo(value){try{const url=new URL(String(value||''),'https://hoshilu.app');if(url.origin!=='https://hoshilu.app'||!url.pathname.startsWith('/')||url.pathname.startsWith('//'))return'/?member=logged-in';return`${url.pathname}${url.search}`;}catch{return'/?member=logged-in';}}
export function lineLoginConfigured(env={}){return /^\d{6,20}$/.test(String(env.LINE_LOGIN_CHANNEL_ID||'').trim())&&Boolean(String(env.LINE_LOGIN_CHANNEL_SECRET||'').trim());}
async function start(request,env){const requestUrl=new URL(request.url),origin=publicOrigin(env);if(requestUrl.origin!==origin)return Response.redirect(`${origin}/api/member/line/start`,302);const channelId=String(env.LINE_LOGIN_CHANNEL_ID||'').trim();if(!lineLoginConfigured(env))return Response.json({ok:false,error:'LINE_LOGIN_NOT_CONFIGURED'},{status:503});const state=random(),nonce=random(),verifier=random(48),returnTo=safeReturnTo(requestUrl.searchParams.get('next'));const flow=await pack({state,nonce,verifier,return_to:returnTo,exp:Math.floor(Date.now()/1000)+600},sessionSecret(env));const url=new URL('https://access.line.me/oauth2/v2.1/authorize');url.search=new URLSearchParams({response_type:'code',client_id:channelId,redirect_uri:callback(env),state,scope:'profile openid',nonce,code_challenge:await sha(verifier),code_challenge_method:'S256'}).toString();return new Response(null,{status:302,headers:{location:url.toString(),'set-cookie':`${OAUTH_COOKIE}=${encodeURIComponent(flow)}; Path=/api/member/line; HttpOnly; Secure; SameSite=Lax; Max-Age=600`}});}
async function finish(request,env){const url=new URL(request.url);try{const flow=await unpack(cookie(request,OAUTH_COOKIE),sessionSecret(env));if(!url.searchParams.get('code')||url.searchParams.get('state')!==flow.state)throw new Error('LINE_LOGIN_STATE_INVALID');const tokenResponse=await fetch('https://api.line.me/oauth2/v2.1/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'authorization_code',code:url.searchParams.get('code'),redirect_uri:callback(env),client_id:String(env.LINE_LOGIN_CHANNEL_ID),client_secret:String(env.LINE_LOGIN_CHANNEL_SECRET),code_verifier:flow.verifier})});if(!tokenResponse.ok)throw new Error('LINE_LOGIN_TOKEN_FAILED');const token=await tokenResponse.json();const verifyResponse=await fetch('https://api.line.me/oauth2/v2.1/verify',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({id_token:token.id_token,client_id:String(env.LINE_LOGIN_CHANNEL_ID),nonce:flow.nonce})});if(!verifyResponse.ok)throw new Error('LINE_LOGIN_ID_TOKEN_INVALID');const profile=await verifyResponse.json();const memberId=await sha(`${profile.sub}:${sessionSecret(env)}`);await storeMemberNotificationDestination(env,memberId,'LINE',String(profile.sub||''));const member=await pack({id:memberId,name:String(profile.name||'').slice(0,80),picture:String(profile.picture||'').startsWith('https://')?profile.picture:'',provider:'LINE',exp:Math.floor(Date.now()/1000)+604800},sessionSecret(env));const headers=new Headers({location:safeReturnTo(flow.return_to)});headers.append('set-cookie',`${SESSION_COOKIE}=${encodeURIComponent(member)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=604800`);headers.append('set-cookie',`${OAUTH_COOKIE}=; Path=/api/member/line; HttpOnly; Secure; SameSite=Lax; Max-Age=0`);return new Response(null,{status:302,headers});}catch{return Response.redirect(`${url.origin}/login.html?error=line`,302);}}
async function issueMemberSession(profile,env){const member=await pack({...profile,exp:Math.floor(Date.now()/1000)+604800},sessionSecret(env));return Response.json({ok:true},{headers:{'cache-control':'no-store','set-cookie':`${SESSION_COOKIE}=${encodeURIComponent(member)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=604800`}});}
async function session(request,env){try{const value=await unpack(cookie(request,SESSION_COOKIE),sessionSecret(env));return Response.json({ok:true,member:{id:value.id,name:value.name,picture:value.picture,provider:value.provider}},{headers:{'cache-control':'no-store'}});}catch{return Response.json({ok:false,member:null},{status:401,headers:{'cache-control':'no-store'}});}}
export async function readMemberSession(request,env){try{const value=await unpack(cookie(request,SESSION_COOKIE),sessionSecret(env));return{id:value.id,name:value.name,picture:value.picture,provider:value.provider};}catch{return null;}}
export async function handleMemberRoutes(request,env){const url=new URL(request.url);if(request.method==='GET'&&url.pathname==='/api/member/line/start')return start(request,env);if(request.method==='GET'&&url.pathname==='/api/member/line/callback')return finish(request,env);if(request.method==='POST'&&url.pathname==='/api/member/email/request')return requestEmailCode(request,env);if(request.method==='POST'&&url.pathname==='/api/member/email/verify')return verifyEmailCode(request,env,issueMemberSession);if(request.method==='POST'&&url.pathname==='/api/member/email/link'){const member=await readMemberSession(request,env);return linkEmailDestination(request,env,member?.id);}if(request.method==='GET'&&url.pathname==='/api/member/session')return session(request,env);if(request.method==='POST'&&url.pathname==='/api/member/logout')return Response.json({ok:true},{headers:{'set-cookie':`${SESSION_COOKIE}=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0`}});return null;}
